# Generated by Django 4.1.7 on 2023-11-09 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.CharField(max_length=100, verbose_name='cafe name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('location', models.URLField(validators=[django.core.validators.URLValidator], verbose_name='location url')),
                ('open', models.CharField(choices=[('5AM', '5AM'), ('6AM', '6AM'), ('7AM', '7AM'), ('8AM', '8AM'), ('9AM', '9AM'), ('10AM', '10AM')], default='9AM', max_length=4, verbose_name='open')),
                ('close', models.CharField(choices=[('5PM', '5PM'), ('6PM', '6PM'), ('7PM', '7PM'), ('8PM', '8PM'), ('9PM', '9PM'), ('10PM', '10PM')], default='5PM', max_length=4, verbose_name='close')),
                ('coffee', models.CharField(choices=[('☕️', '☕️'), ('☕️☕️', '☕️☕️'), ('☕️☕️☕️', '☕️☕️☕️'), ('☕️☕️☕️☕️', '☕️☕️☕️☕️'), ('☕️☕️☕️☕️️☕️', '☕️☕️☕️☕️️☕️'), ('✘', '✘')], default='☕️', max_length=11, verbose_name='coffee rating')),
                ('wifi', models.CharField(choices=[('💪️', '💪️'), ('💪️💪️', '💪️💪️'), ('💪️💪️💪️', '💪️💪️💪️'), ('💪️💪️💪️💪️', '💪️💪️💪️💪️'), ('💪️💪️💪️💪️💪️', '💪️💪️💪️💪️💪️'), ('✘', '✘')], default='💪️', max_length=10, verbose_name='wifi rating')),
                ('power', models.CharField(choices=[('🔌', '🔌'), ('🔌🔌', '🔌🔌'), ('🔌🔌🔌', '🔌🔌🔌'), ('🔌🔌🔌🔌', '🔌🔌🔌🔌'), ('🔌🔌🔌🔌🔌', '🔌🔌🔌🔌🔌'), ('✘', '✘')], default='🔌', max_length=5, verbose_name='power outlet rating')),
            ],
        ),
    ]
